include:
  - ./gatewayService/compose.yaml
  - ./authService/compose.yaml
  - ./studyPlansService/compose.yaml
  - ./notificationService/compose.yaml
  - ./userService/compose.yaml

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge