include:
  - ./gatewayService/compose.yaml
  - ./authService/compose.yaml
  - ./studyPlansService/compose.yaml
  - ./notificationService/compose.yaml
  - ./userService/compose.yaml

networks:
  microservices-network:
    driver: bridge