services:
  api-gateway:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - authentication-service
      - study-plans-service
      - notifications-service
      - users-service
    networks:
      - microservices-network