services:
  users-service:
    build: .
    ports:
      - "8004:8004"
    depends_on:
      - users-db
    networks:
      - microservices-network

  users-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "users-database"
    ports:
      - "5436:5432"
    networks:
      - microservices-network