app:
  gateway:
    authentication-service:
      target-url: http://localhost:8001
    notification-service:
      target-url: http://localhost:8000
    study-plans-service:
      target-url: http://localhost:8002

spring:
  application:
    name: r2l-API-gateway

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/auth/**
            - Path=/api/auth # <<<<<<<<<<<<< Adicionei esta linha anteriormente
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway-Token,${GATEWAY_SECRET:r2l-gateway-secret}

        - id: notification-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway-Token,${GATEWAY_SECRET:r2l-gateway-secret}

        - id: study-plans-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/study-plans/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway-Token,${GATEWAY_SECRET:r2l-gateway-secret}

server:
  port: 8080

# Configurações para resolver problemas de inicialização
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    root: INFO

# Configurações de health check
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized