app:
  gateway:
    authentication-service:
      target-url: http://localhost:8001
    notification-service:
      target-url: http://localhost:8000
    study-plans-service:
      target-url: http://localhost:8002

spring:
  application:
    name: r2l-API-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: authentication-service
            uri: http://localhost:8001
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=1
              - AddRequestHeader=X-Gateway-Token,${GATEWAY_SECRET:r2l-gateway-secret}

          - id: notification-service
            uri: http://localhost:8000
            predicates:
              - Path=/api/notification/**
            filters:
              - StripPrefix=2
              - AddRequestHeader=X-Gateway-Token,${GATEWAY_SECRET:r2l-gateway-secret}

          - id: study-plans-service
            uri: http://localhost:8002
            predicates:
              - Path=/api/study-plans/**
            filters:
              - StripPrefix=2
              - AddRequestHeader=X-Gateway-Token,${GATEWAY_SECRET:r2l-gateway-secret}
server:
  port: 8080