services:
  authentication-service:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - authentication-db
    networks:
      - microservices-network

  authentication-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "authentication-database"
    ports:
      - "5433:5432"
    networks:
      - microservices-network